#!/usr/bin/env python3
"""Generate ACCURACY.md from adapter fixtures with expected token sidecars."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ACCURACY.md"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _adapter_label(adapter_cls: type[object]) -> str:
    base = adapter_cls.__name__.removesuffix("Adapter")
    return re.sub(r"(?<!^)(?=[A-Z])", "_", base).lower()


def _mape(expected_total: int, actual_total: int) -> float:
    denom = max(expected_total, 1)
    return abs(actual_total - expected_total) / denom * 100.0


def _sidecar_path(fixture: Path) -> Path:
    return fixture.with_suffix(f"{fixture.suffix}.expected_tokens.json")


def _token_method(pct_estimated: float, total_tokens: int) -> str:
    if total_tokens <= 0:
        return "absent"
    return "estimated" if pct_estimated > 0 else "measured"


def render() -> str:
    from server.util.ids import new_ulid
    from tests.adapter_conformance import ADAPTER_FIXTURES

    rows: list[tuple[str, str, float, str]] = []
    for adapter_cls, fixture in ADAPTER_FIXTURES:
        sidecar = _sidecar_path(fixture)
        if not sidecar.is_file():
            continue
        expected = json.loads(sidecar.read_text(encoding="utf-8"))
        expected_input = int(expected.get("input_tokens", 0))
        expected_output = int(expected.get("output_tokens", 0))
        expected_total = expected_input + expected_output

        adapter = adapter_cls(ROOT, new_ulid())
        parsed = adapter.parse_path(fixture)
        if parsed is None:
            raise ValueError(f"failed to parse fixture: {fixture}")
        trace, _spans, quality = adapter.to_spans(parsed, workspace_id=new_ulid(), repo_root=ROOT)
        actual_total = int(trace.input_tokens) + int(trace.output_tokens)
        pct_estimated = float(quality.pct_tokens_estimated or 0.0)
        method = _token_method(pct_estimated, actual_total)
        note = str(expected.get("note", fixture.name))
        rows.append(
            (_adapter_label(adapter_cls), method, _mape(expected_total, actual_total), note)
        )

    rows.sort(key=lambda row: row[0])
    lines = [
        "# Accuracy and estimation honesty",
        "",
        "> Auto-generated by `scripts/gen_accuracy.py`. Do not edit by hand.",
        "",
        "| Adapter | Token method | MAPE | Notes |",
        "|---------|--------------|------|-------|",
    ]
    if not rows:
        lines.append("| *no sidecar fixtures* | — | — | Add `*.expected_tokens.json` fixtures |")
    else:
        for adapter, method, mape_pct, note in rows:
            lines.append(f"| `{adapter}` | {method} | {mape_pct:.2f}% | {note} |")
    lines.extend(
        [
            "",
            "## What “estimated” means",
            "",
            "- **Measured** — token counts reported by the agent runtime or OTLP ingest.",
            (
                "- **Estimated** — derived from heuristics (chars/4, tiktoken when "
                "`precise` extra installed, model-specific tables)."
            ),
            (
                "- **Absent** — no usage data; cost may still be priced from model defaults "
                "with explicit `cost_source`."
            ),
            "",
            (
                "Verdicts in Optimize use anytime-valid confidence sequences with clustered "
                "effective sample sizes — not fixed-width CIs under continuous monitoring."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
