#!/usr/bin/env python3
"""Generate docs/cli.md from the Typer CLI surface and action registry."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "cli.md"

HEADER = """# CLI reference

> Auto-generated by `scripts/gen_cli_docs.py`. Do not edit by hand.

Cairn CLI entry point: `server.cli:app`. Mutations are also available as `cairn action <name>`.

## Top-level commands

| Command | Description |
|---------|-------------|
"""

ACTION_HEADER = """
## Action registry

Run with `cairn action <name> [--params-json '{}']`.

| Action | Category | Title | Async |
|--------|----------|-------|-------|
"""

CONTRACTS = """
## Stable JSON schemas

Read-only `--json` commands emit a versioned envelope:

| Command | `schema` | Payload |
|---------|----------|---------|
| `cairn stats --json` | `cairn.stats.v1` | Budget burn body (spend, projections, shares, ledger) |
| `cairn guard --json` | `cairn.guard.v1` | Guard analytics body (days, ledger, events) |
| `cairn top --json` | `cairn.top.v1` | `{days, limit, rows[]}` session spend snapshot |
| `cairn why --json` | `cairn.why.v1` | `{trace_id, available, message, postmortem}` |
| `cairn receipt --json` | `cairn.receipt.v1` | Verification receipt body (status, debt, timeline) |
| `cairn handoff --json` | `cairn.handoff.v1` | Offline handoff capsule |
| `cairn review --json` | `cairn.review.v1` | Advisory review queue (not employee ranking) |
| `cairn verify next --json` | `cairn.verify.next.v1` | Next-check preview (never executes) |
| `cairn resource --json` | `cairn.resource.v1` | Partial local footprint inventory |
| `cairn privacy --json` | `cairn.privacy.v1` | Local-first privacy posture |
| `cairn regression * --json` | `cairn.regression.v1` | Artifact / validate / import-export bodies |

Every envelope includes `schema` and `generated_at` (UTC ISO-8601). Field bodies match the
corresponding API/payload models unless noted.

## Exit codes

| Code | Meaning |
|------|---------|
| `0` | Success |
| `1` | Generic failure (missing resource, failed gate, updater error, server stop miss) |
| `2` | `cairn why` missing postmortem; `cairn regression validate` schema/honesty errors |

`cairn top` exits `0` on Ctrl-C after a clean shutdown. Non-TTY stdout forces a single snapshot
(same as `--once`).
"""


def _command_label(cmd: object) -> str | None:
    name = getattr(cmd, "name", None)
    if name:
        return str(name).replace("_", "-")
    callback = getattr(cmd, "callback", None)
    raw = getattr(callback, "__name__", "") or ""
    aliases = {"show_trace": "show", "setup_prompt": "setup-prompt", "mcp_install_cmd": "install"}
    return aliases.get(raw, raw.replace("_", "-")) or None


def _typer_rows() -> list[tuple[str, str]]:
    from server.cli import app

    rows: list[tuple[str, str]] = []
    for cmd in app.registered_commands:
        label = _command_label(cmd)
        if not label:
            continue
        doc = (cmd.help or cmd.callback.__doc__ or "").strip().split("\n")[0]
        rows.append((f"`cairn {label}`", doc))
    for group in app.registered_groups:
        gname = group.name or ""
        if group.typer_instance.registered_callback is not None:
            callback = group.typer_instance.registered_callback
            doc = (group.help or callback.callback.__doc__ or "").strip().split("\n")[0]
            rows.append((f"`cairn {gname}`", doc))
        for sub in group.typer_instance.registered_commands:
            sublabel = _command_label(sub)
            if not sublabel:
                continue
            doc = (sub.help or sub.callback.__doc__ or "").strip().split("\n")[0]
            rows.append((f"`cairn {gname} {sublabel}`", doc))
    return sorted(rows, key=lambda r: r[0])


def _action_rows() -> list[tuple[str, str, str, str]]:
    from server.api.actions import build_manifest

    rows: list[tuple[str, str, str, str]] = []
    for entry in sorted(build_manifest(), key=lambda e: e.name):
        async_flag = "yes" if entry.async_job else "no"
        rows.append((entry.name, entry.category, entry.title, async_flag))
    return rows


def render() -> str:
    lines = [HEADER.rstrip()]
    for cmd, doc in _typer_rows():
        lines.append(f"| {cmd} | {doc} |")
    lines.append(ACTION_HEADER.rstrip())
    for name, category, title, async_flag in _action_rows():
        lines.append(f"| `{name}` | {category} | {title} | {async_flag} |")
    lines.append(CONTRACTS.rstrip())
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
