#!/usr/bin/env python3
"""Generate ACCURACY.md from adapter fixtures with expected token sidecars."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ACCURACY.md"
DATA_OUT = ROOT / "server" / "ingest" / "accuracy_data.json"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _mape(expected_total: int, actual_total: int) -> float:
    denom = max(expected_total, 1)
    return abs(actual_total - expected_total) / denom * 100.0


def _sidecar_path(fixture: Path) -> Path:
    return fixture.with_suffix(f"{fixture.suffix}.expected_tokens.json")


def _token_method(pct_estimated: float, total_tokens: int) -> str:
    if total_tokens <= 0:
        return "absent"
    return "estimated" if pct_estimated > 0 else "measured"


def measure() -> list[dict[str, object]]:
    """Measure token error and fixture parse coverage for every adapter."""
    from server.ingest.parse_health import inspect_unknown_fields
    from server.util.ids import new_ulid
    from tests.adapter_conformance import ADAPTER_FIXTURES

    rows: list[dict[str, object]] = []
    for adapter_cls, fixture in ADAPTER_FIXTURES:
        adapter = adapter_cls(ROOT, new_ulid())
        parsed = adapter.parse_path(fixture)
        unknown = inspect_unknown_fields(adapter.adapter_id, fixture)
        fully_parsed = bool(parsed is not None and parsed.dropped_events == 0 and not unknown)
        row: dict[str, object] = {
            "adapter_id": adapter.adapter_id,
            "parse_coverage_pct": 100.0 if fully_parsed else 0.0,
            "fully_parsed_fixtures": 1 if fully_parsed else 0,
            "fixture_attempts": 1,
            "method": "absent",
            "mape_pct": None,
            "note": f"{fixture.name}; no expected-token sidecar",
        }
        sidecar = _sidecar_path(fixture)
        if not sidecar.is_file():
            rows.append(row)
            continue
        expected = json.loads(sidecar.read_text(encoding="utf-8"))
        expected_input = int(expected.get("input_tokens", 0))
        expected_output = int(expected.get("output_tokens", 0))
        expected_total = expected_input + expected_output

        if parsed is None:
            raise ValueError(f"failed to parse fixture: {fixture}")
        trace, _spans, quality = adapter.to_spans(parsed, workspace_id=new_ulid(), repo_root=ROOT)
        actual_total = int(trace.input_tokens) + int(trace.output_tokens)
        pct_estimated = float(quality.pct_tokens_estimated or 0.0)
        method = _token_method(pct_estimated, actual_total)
        note = str(expected.get("note", fixture.name))
        row.update(
            {
                "method": method,
                "mape_pct": _mape(expected_total, actual_total),
                "note": note,
            }
        )
        rows.append(row)

    return sorted(rows, key=lambda row: str(row["adapter_id"]))


def render(rows: list[dict[str, object]] | None = None) -> str:
    rows = rows or measure()

    lines = [
        "# Accuracy and estimation honesty",
        "",
        "> Auto-generated by `scripts/gen_accuracy.py`. Do not edit by hand.",
        "",
        "| Adapter | Fixture parse coverage | Token method | MAPE | Notes |",
        "|---------|------------------------|--------------|------|-------|",
    ]
    if not rows:
        lines.append("| *no fixtures* | — | — | — | Add an adapter conformance fixture |")
    else:
        for row in rows:
            mape = row["mape_pct"]
            mape_text = f"{float(mape):.2f}%" if mape is not None else "—"
            lines.append(
                f"| `{row['adapter_id']}` | {row['fully_parsed_fixtures']}/"
                f"{row['fixture_attempts']} ({float(row['parse_coverage_pct']):.0f}%) | "
                f"{row['method']} | {mape_text} | {row['note']} |"
            )
    lines.extend(
        [
            "",
            "## Parse coverage methodology",
            "",
            (
                "Fixture parse coverage is a CI canary: a fixture counts as fully parsed only "
                "when parsing succeeds with zero dropped events and zero unknown top-level fields."
            ),
            (
                "Each built-in adapter currently has one conformance fixture, so `1/1 (100%)` "
                "does not claim 100% production reliability. Live workspace coverage in Settings "
                "is measured across actual changed-stream parse attempts."
            ),
            "",
            "## What “estimated” means",
            "",
            "- **Measured** — token counts reported by the agent runtime or OTLP ingest.",
            (
                "- **Estimated** — derived from heuristics (chars/4, tiktoken when "
                "`precise` extra installed, model-specific tables)."
            ),
            (
                "- **Absent** — no usage data; cost may still be priced from model defaults "
                "with explicit `cost_source`."
            ),
            "",
            (
                "Verdicts in Optimize use anytime-valid confidence sequences with clustered "
                "effective sample sizes — not fixed-width CIs under continuous monitoring."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    rows = measure()
    OUT.write_text(render(rows), encoding="utf-8")
    accuracy_data = {
        str(row["adapter_id"]): {
            "method": row["method"],
            "mape_pct": row["mape_pct"],
            "note": row["note"],
            "parse_coverage_pct": row["parse_coverage_pct"],
        }
        for row in rows
    }
    DATA_OUT.write_text(
        json.dumps(accuracy_data, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"Wrote {OUT} and {DATA_OUT}")


if __name__ == "__main__":
    main()
